"""
Stats Agent for Cricket AI Council.

Analyzes historical aggregate statistics (career averages, strike rates, head-to-head records)
to produce a baseline prediction for a given cricket question.

This agent queries the pre-processed matches.csv and deliveries.csv files generated by
data/load_cricsheet.py.

Example question formats this agent handles:
- "Will Team A win the toss-and-bat gamble at Venue X?"
- "Which batter will score the most runs in Match Y?"
- "Who has the better head-to-head record: Player A vs Player B at Venue Z?"
"""
import pandas as pd
from pathlib import Path
from agents.base_agent import BaseAgent, AgentVerdict

DATA_DIR = Path(__file__).parent.parent / "data" / "processed"


class StatsAgent(BaseAgent):
    name = "stats"

    def __init__(self, matches_df: pd.DataFrame, deliveries_df: pd.DataFrame):
        self.matches = matches_df
        self.deliveries = deliveries_df
        self._precompute_aggregates()

    def _precompute_aggregates(self):
        """Precompute career-level aggregates for all players."""
        batsmen = (
            self.deliveries[self.deliveries['is_legal_delivery'] == True]
            .groupby('batter')
            .agg(
                runs_scored=('runs_batter', 'sum'),
                balls_faced=('runs_batter', 'count'),
                times_out=('is_wicket', 'sum'),
                innings=('match_id', 'nunique')
            )
            .reset_index()
        )
        batsmen['career_average'] = batsmen['runs_scored'] / batsmen['times_out'].clip(lower=1)
        batsmen['strike_rate'] = (batsmen['runs_scored'] / batsmen['balls_faced']) * 100
        self.batsmen_stats = batsmen

        bowlers = (
            self.deliveries[self.deliveries['is_legal_delivery'] == True]
            .groupby('bowler')
            .agg(
                runs_conceded=('runs_total', 'sum'),
                balls_bowled=('runs_total', 'count'),
                wickets_taken=('is_wicket', 'sum'),
                matches=('match_id', 'nunique')
            )
            .reset_index()
        )
        bowlers['economy'] = (bowlers['runs_conceded'] / bowlers['balls_bowled']) * 6
        bowlers['average'] = bowlers['runs_conceded'] / bowlers['wickets_taken'].clip(lower=1)
        self.bowlers_stats = bowlers

        team_records = (
            self.matches.dropna(subset=['winner'])
            .groupby('team1')
            .agg(
                matches_played=('match_id', 'count'),
                matches_won=('winner', lambda x: (x == x.name).sum())
            )
            .reset_index()
        )
        team_records['win_pct'] = team_records['matches_won'] / team_records['matches_played']
        self.team_stats = team_records

    def analyze(self, question: dict) -> AgentVerdict:
        """
        question dict expected keys:
        - type: one of ['toss_bat_gamble', 'top_scorer', 'head_to_head']
        - teams: list of team names (for toss_bat_gamble)
        - venue: optional venue string
        - players: list of player names (for top_scorer or head_to_head)
        - match_id: optional specific match to filter
        """
        q_type = question.get('type')
        if q_type == 'toss_bat_gamble':
            return self._predict_toss_bat_gamble(question)
        elif q_type == 'top_scorer':
            return self._predict_top_scorer(question)
        elif q_type == 'head_to_head':
            return self._predict_head_to_head(question)
        else:
            raise ValueError(f"Unknown question type: {q_type}")

    def _predict_toss_bat_gamble(self, question: dict) -> AgentVerdict:
        teams = question.get('teams', [])
        venue = question.get('venue')
        if len(teams) != 2:
            raise ValueError("toss_bat_gamble requires exactly 2 teams")
        
        venue_matches = self.matches if venue is None else self.matches[self.matches['venue'].str.contains(venue, case=False, na=False)]
        team1 = teams[0]
        team2 = teams[1]
        
        t1_wins = venue_matches[(venue_matches['team1'].isin([team1, team2])) & (venue_matches['winner'] == team1)].shape[0]
        t2_wins = venue_matches[(venue_matches['team1'].isin([team1, team2])) & (venue_matches['winner'] == team2)].shape[0]
        total = t1_wins + t2_wins
        
        if total == 0:
            prediction = f"No historical data for {team1} vs {team2} at {venue}"
            confidence = 0.1
            t1_pct = 0.5
        else:
            t1_pct = t1_wins / total
            prediction = team1 if t1_pct > 0.5 else team2
            confidence = max(t1_pct, 1 - t1_pct)
        
        reasoning = f"At {venue or 'all venues'}, {team1} won {t1_wins}/{total} ({t1_pct:.1%}) vs {team2} won {t2_wins}/{total}. Prediction: {prediction}."
        return AgentVerdict(agent_name=self.name, prediction=prediction, confidence=confidence, reasoning=reasoning)

    def _predict_top_scorer(self, question: dict) -> AgentVerdict:
        players = question.get('players', [])
        if not players:
            raise ValueError("top_scorer requires a list of players")
        player_stats = self.batsmen_stats[self.batsmen_stats['batter'].isin(players)]
        if player_stats.empty:
            return AgentVerdict(self.name, None, 0.1, f"No career data for {players}")
        top = player_stats.loc[player_stats['career_average'].idxmax()]
        return AgentVerdict(self.name, top['batter'], 0.6, f"Career avg: {top['career_average']:.1f}, SR: {top['strike_rate']:.1f}")

    def _predict_head_to_head(self, question: dict) -> AgentVerdict:
        players = question.get('players', [])
        venue = question.get('venue')
        if len(players) != 2:
            raise ValueError("head_to_head requires exactly 2 players")
        p1 = self.batsmen_stats[self.batsmen_stats['batter'] == players[0]]
        p2 = self.batsmen_stats[self.batsmen_stats['batter'] == players[1]]
        if p1.empty or p2.empty:
            return AgentVerdict(self.name, None, 0.1, f"Missing career data for {players}")
        p1_avg = p1.iloc[0]['career_average']
        p2_avg = p2.iloc[0]['career_average']
        winner = players[0] if p1_avg > p2_avg else players[1]
        confidence = 0.5 + 0.1 * abs(p1_avg - p2_avg) / max(p1_avg, p2_avg, 1)
        return AgentVerdict(self.name, winner, min(confidence, 0.95), f"{players[0]} avg {p1_avg:.1f} vs {players[1]} avg {p2_avg:.1f}")


if __name__ == "__main__":
    matches_df = pd.read_csv(DATA_DIR / "matches.csv")
    deliveries_df = pd.read_csv(DATA_DIR / "deliveries.csv")
    agent = StatsAgent(matches_df, deliveries_df)
    q = {"type": "toss_bat_gamble", "teams": ["Chennai Super Kings", "Mumbai Indians"], "venue": "Wankhede"}
    v = agent.analyze(q)
    print(v)
